steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sample-product-catalog/ecofusion:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sample-product-catalog/ecofusion:$COMMIT_SHA']
# Deploy container image to GKE
- name: 'gcr.io/cloud-builders/sample-product-catalogecofusion'
  args:
  - run
  - --filename=k8s-deployment.yaml
  - --image=gcr.io/sample-product-catalog/ecofusion:$COMMIT_SHA
  - --location=us-central1-a  # Replace with your GKE cluster's region
  - --cluster=ecofusion  # Replace with your GKE cluster's name

# Use Cloud Logging Only for logs
options:
  logging: CLOUD_LOGGING_ONLY

images:
- gcr.io/sample-product-catalog/ecofusion:$COMMIT_SHA
