steps:
- name: 'gcr.io/cloudbuild/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/sample-product-catalog/my-website-repo/my-website:latest', '.']
- name: 'gcr.io/cloudbuild/docker'
  args: ['push', 'us-central1-docker.pkg.dev/sample-product-catalog/my-website-repo/my-website:latest']
- name: 'gcr.io/cloudbuild/kubectl'
  args: ['apply', '-f', 'deployment.yaml']
- name: 'gcr.io/cloudbuild/kubectl'
  args: ['apply', '-f', 'service.yaml']
- name: 'gcr.io/cloudbuild/kubectl'
  args: ['apply', '-f', 'ingress.yaml']

