apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
  namespace: ecofusion-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
      - name: nextjs-container
        image: gcr.io/eco-fusion-429815/nextjs-app:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      imagePullSecrets:
      - name: gcr-json-key
