
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecofusion
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecofusion
  template:
    metadata:
      labels:
        app: ecofusion
    spec:
      serviceAccountName: ecofusion-ksa
      containers:
      - name: ecofusion
        image: us-central1-docker.pkg.dev/excellent-nexus-431107-n8/my-repo/ecofusion:v1
        ports:
        - containerPort: 80
