apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecofusion-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "ghumanportfolio"
spec:
  defaultBackend:
    service:
      name: ecofusion
      port: 
        number: 80